steps:
  # Passo 1: Build .net app
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    args: ['dotnet', 'build', '-c', 'Release']

  # Passo 2: Publish .net app
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    args: ['dotnet', 'publish', '-c', 'Release', '-o', './publish']

  # Passo 3: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      docker build -t gcr.io/$PROJECT_ID/my-app:$SHORT_SHA .
  
  # Passo 4: Push image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA']

images:
  - 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA'
