steps:
  # Passo 1: Build .net app
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    args: ['build', '-c', Release]

  # Passo 2: publish
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    args: ['publish', '-c', Release, '-o', './publish']

  # Passo 3: build docker img
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA', '.']

  # Passo 4: push image to Google Container Registry
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA']

images:
  - 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA'
